---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - node
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**.*.js"
exclude_paths:
  - node_modules/**/*
  - src/**.*.test.js
